services:
  - type: web
    name: handwriting-to-text
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
